// This file is generated by npm run build:icons

export type IconName =
	| "radix/avatar"
	| "radix/boy"
	| "radix/clock"
	| "radix/comic"
	| "radix/completed"
	| "radix/desktop"
	| "radix/fire"
	| "radix/girl"
	| "radix/history"
	| "radix/link-1"
	| "radix/link-2"
	| "radix/moon"
	| "radix/new"
	| "radix/popular"
	| "radix/recently"
	| "radix/sun"
	| "radix/top"
	| "radix/trending";
